# Generated by Django 2.1.15 on 2022-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_empleado', models.IntegerField()),
                ('Nombre', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=255)),
                ('Area', models.CharField(max_length=255)),
                ('Spot', models.CharField(blank=True, max_length=255)),
                ('Supervisor', models.CharField(blank=True, max_length=255)),
                ('Correo', models.EmailField(max_length=254)),
                ('CorreoSupervisor', models.EmailField(max_length=254)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
