# Generated by Django 2.1.15 on 2022-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='CorreoSupervisor',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
