# Generated by Django 2.1.15 on 2022-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20221010_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
