# Generated by Django 4.0.8 on 2022-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Correo',
            field=models.EmailField(blank=True, default='default_email@vertiv.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='CorreoSupervisor',
            field=models.EmailField(blank=True, default='default_email@vertiv.com', max_length=254),
        ),
    ]
