# Generated by Django 4.0.8 on 2022-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_empleado_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ID_empleado',
            field=models.CharField(max_length=255),
        ),
    ]
